export const columns = [
  {
    title: "Ticker",
    dataIndex: "ticker",
    key: "ticker",
    align: "center",
    width: "100px",
    className: "text",
  },
  {
    title: "Exchange",
    dataIndex: "exchange",
    key: "exchange",
    align: "center",
    width: 100,
    className: "text",
  },
  {
    title: "Price",
    dataIndex: "price",
    key: "price",
    align: "center",
    width: 100,
  },
  {
    title: "Change",
    dataIndex: "change",
    key: "change",
    align: "center",
    width: 100,
  },
  {
    title: "Percent",
    dataIndex: "change_percent",
    key: "change_percent",
    align: "center",
    width: 100,
  },
  {
    title: "Dividend",
    dataIndex: "dividend",
    key: "dividend",
    align: "center",
    width: 100,
  },
  {
    title: "Last trade",
    dataIndex: "last_trade_time",
    key: "last_trade_time",
    align: "center",
    width: 200,
    className: "text",
  },
];
